import { Inter } from 'next/font/google'
import './globals.css'
import { PrimeReactProvider } from 'primereact/api';
// import { headers } from 'next/navigation';

import "primereact/resources/themes/saga-blue/theme.css";
import "primereact/resources/primereact.min.css";
import {Sidebar, SidebarItem} from '@/components/Sidebar'
import { LifeBuoy, Receipt, Boxes, Package, UserCircle, BarChart3, LayoutDashboard, Settings } from 'lucide-react'
import { isLogin } from "@/utlis/session"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Control Tower',
  description: 'Generated by Fastmart',
}
  const session = isLogin
  console.log('session', session)

export default function RootLayout({ children }) {
  return (
    <PrimeReactProvider>
    <html lang="en">

      <body className={inter.className}>
        <div className='flex bg-gray-100 h-screen'>
          {session && 
          <Sidebar>
          
            <SidebarItem icon={<LayoutDashboard size={20}/> } text="Dashboard" alert/>
            <SidebarItem icon={<BarChart3 size={20} />} text="Statistics" active/>
            <SidebarItem icon={<UserCircle size={20} />} text="Users" />
            <SidebarItem icon={<Boxes size={20} />} text="Inventory" />
            <SidebarItem icon={<Package size={20} />} text="Orders" alert/>
            <SidebarItem icon={<Receipt size={20} />} text="Billings" />
            <hr className='my-3'/>
            <SidebarItem icon={<Settings size={20} />} text="Settings" />
            <SidebarItem icon={<LifeBuoy size={20} />} text="Help" />
          </Sidebar>
          }
          
          {children}
        </div>
      </body>
    </html>
      </PrimeReactProvider>
  )
}
